### ISSUE TITLE
 Ixalan standard cards causes IndexOutOfBoundsException in MCTSAI.growTree

### ISSUE THREAD

**Issue by Fulmene** [magarena/magarena#1513] opened 2018-03-20 09:16 UTC
[1521489347.zip](https://github.com/magarena/magarena/files/1828605/1521489347.zip)

**Comment by Fulmene** [comment] 2018-03-20 09:16
I'm not sure if this issue is related to #1506, so I open a new issue here.

**Comment by melvinzhang** [comment] 2018-03-20 09:40
Most likely not related to #1506, but similar to #1502 but probably for a different reason that the game presents different options. In this case, in one iteration of the AI the game had 3 options to choose from, but in another iteration it has less than 3 options.

**Comment by melvinzhang** [comment] 2018-03-20 10:11
Ah, now I see what you mean by related to #1506. Explore is affected by #1506, but from what I can tell it should not cause a crash just that the moving of the card would fail.

**Comment by Fulmene** [comment] 2018-03-20 15:38
So you're saying Explore is affected by #1506, but this particular crash isn't? I also thought so.

The problem in this crash seems to be how the AI had 3 options, while Exploring a nonland card usually only has 2 options (put it to the graveyard, or not) (I think?). So in which case would Explore has 3 options?

FYI, I limited the cards in testing to only Ixalan Standard cards in my test server.

**Comment by melvinzhang** [comment] 2018-03-21 01:34
It isn't clear that this crash is due to Explore, since it could just be a coincidence that Explore was there. It will be good to collect other cases of this occurring in the test games you are running here as well. 

This particular problem is easier to debug with assertions enabled, please add `flags=-ea` to your test games, eg `make flags=-ea games=50 ai1=MMABC ai2=MCTS ${MAG_ID}.t` This will show us what the options actual 2/3+ ptions are.

The way it works is that MCTSAI saves the situations it has considered in a previous turn, then at this turn if it noticed it has seen this situation before, it will reuse what it has done earlier.

Let's call the earlier situation A, and the current situation B. There are typically two kinds problem

1) B and A are not actually the same. This occurs if there is some hidden state in A or B that is not used in comparing them. The comparison is done with MagicGame.getStateId.

2) B and A are the same, but at some future point they diverge. This is due to use of certain methods that introduce difference between them such as Collections.shuffle.

**Comment by Fulmene** [comment] 2018-03-22 12:48
I found error in [this build](https://circleci.com/gh/Fulmene/magarena/471). The message now reports assertion error instead of exception so I'm not sure it's the same deal, but I'll just post it here.

**Comment by melvinzhang** [comment] 2018-03-22 13:20
The asserts will hopefully catch the bug closer to the source, assertion error is correct. Though this is one I've not seen in a long time, long enough that I forgot why I put that assertion there in the first place... well more examples will help us find a common pattern in them.

**Comment by Fulmene** [comment] 2018-03-22 14:08
Got the same assertion error again. [CI build](https://circleci.com/gh/Fulmene/magarena/478)

```
293. ExecuteFirstEventAction = 0
294. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
295. ExecuteFirstEventAction = 0
296. AddEventAction (EVENT: NONE  Declare blockers.) = 0
297. ExecuteFirstEventAction = 0
298. DeclareBlockersAction = 0
299. DeclareBlockerAction = 0
300. SetBlockerAction = 0
301. ChangeStateAction = 0
302. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
303. ExecuteFirstEventAction = 0
304. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
305. ExecuteFirstEventAction = 0
306. CombatDamageAction = 0
307. CombatDamageAction = 0
308. DealDamageAction = 0
309. ChangeStateAction = 0
310. DealDamageAction = 0
311. ChangeStateAction = 0
312. DestroyAction = 0
313. RemoveAllFromPlayAction = 0
314. RemoveFromPlayAction (Jungle Delver,0) = 800
315. RemoveFromCombatAction (Jungle Delver) = 0
316. ChangeStateAction = 0
317. ChangeStateAction = 0
318. MoveCardAction (Jungle Delver,Battlefield,Graveyard) = 0
319. ChangePlayerStateAction = 0
320. RemoveTriggersStaticsAction = 0
321. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
322. ExecuteFirstEventAction = 0
323. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
324. ExecuteFirstEventAction = 0
325. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
326. ExecuteFirstEventAction = 0
327. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
328. ExecuteFirstEventAction = 0
329. RemoveFromCombatAction (Steward of Solidarity) = 0
330. ChangeStateAction = 0
331. ChangeStateAction = 0
332. ChangeStateAction = 0
333. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = 1122

Exception from controller.runGame: ERROR! length of MCTS path is 1
java.lang.AssertionError: ERROR! length of MCTS path is 1
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


6 2108297149 1112737073 1 0 1 0 -1 -1 -1 -1785884467661127700 382790725146443516 382790725146443516 -142125129646518675 2159627630915701653 -9045168381211715873 10000001 -7582093024508167540 634501190076685941 382790725146443516
10 0 0 0 0 0 0 0 0 0 7 0 0 0 0 1016747763302421367 -1110823358259909857 382790725146443516 382790725146443516 -8933703120587815218 0 -1 -1 0
10 0 0 0 0 0 0 0 0 1 7 0 0 0 0 1864417210983963583 -8215684272733141906 6520271224713142806 382790725146443516 -3437350222578792682 0 -1 -1 0
ADDED: GAME: id=-336013781820376160 t=6 p=FirstMain s=ActivePlayer tp=1 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0
6 2108297149 1112737073 1 0 1 0 -1 -1 -1 -1785884467661127700 382790725146443516 382790725146443516 -142125129646518675 2159627630915701653 -1509045686172630477 10000001 -7582093024508167540 634501190076685941 382790725146443516
10 0 0 0 0 0 0 0 0 0 7 0 0 0 0 1016747763302421367 -1110823358259909857 382790725146443516 382790725146443516 -8933703120587815218 0 -1 -1 0
8 0 0 0 0 0 0 0 0 1 7 0 0 0 0 1864417210983963583 -8215684272733141906 382790725146443516 382790725146443516 -8148843068709986743 0 -1 -1 0
ADDED: GAME: id=-1933687270060177620 t=6 p=FirstMain s=ActivePlayer tp=1 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0
6 2108297149 1112737073 1 0 1 0 -1 -1 -1 -1785884467661127700 382790725146443516 382790725146443516 -142125129646518675 -8772105398100260862 -9045168381211715873 10000001 -7582093024508167540 634501190076685941 382790725146443516
10 0 0 0 0 0 0 0 0 0 7 0 0 0 0 -6260974791366652670 -1110823358259909857 382790725146443516 382790725146443516 4132023453280842500 0 -1 -1 0
10 0 0 0 0 0 0 0 0 1 7 0 0 0 0 1864417210983963583 -8215684272733141906 6520271224713142806 382790725146443516 -3437350222578792682 0 -1 -1 0
ADDED: GAME: id=4097884063218763587 t=6 p=FirstMain s=ActivePlayer tp=1 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0
6 2108297149 1112737073 1 0 1 0 -1 -1 -1 -1785884467661127700 382790725146443516 382790725146443516 -142125129646518675 1017218695429304954 -9045168381211715873 10000001 -7582093024508167540 634501190076685941 382790725146443516
10 0 0 0 0 2 0 0 0 0 7 0 0 1 0 5330975168293046869 -1110823358259909857 382790725146443516 382790725146443516 -2061952613639038139 0 -1 -1 0
10 0 0 0 0 0 0 0 0 1 7 0 0 0 0 1864417210983963583 -8215684272733141906 6520271224713142806 382790725146443516 -3437350222578792682 0 -1 -1 0
MCTS cheat=true index=1 life=10 turn=5 phase=DeclareBlockers sims=33 time=2318
* [22/27/?] (S-799 Steward of Solidarity=Jungle Delver)
  [3/6/?] (S-999)
LOG (C): MCTSC blocks with <Jungle Delver~1000063>.
LOG (C): <Jungle Delver~1000063> is destroyed.
Makefile:229: recipe for target 'circleci' failed
make: *** [circleci] Error 1
Exited with code 2
```

**Comment by Fulmene** [comment] 2018-03-22 19:03
Inconsistent node found. [CI build](https://circleci.com/gh/Fulmene/magarena/486)

```
1940. TapAction (Treasure Map) = -5
1941. AddEventAction (EVENT: Treasure Map Pay {1}$. Choose how to pay the mana cost.) = 0
1942. AddEventAction (EVENT: Treasure Map Play activated ability of <Treasure Map~1000013>. ) = 0
1943. ExecuteFirstEventAction = 0
1944. TapAction (Concealed Courtyard) = -5
1945. ExecuteFirstEventAction = 0
1946. PutItemOnStackAction (MagicAbilityOnStack,Treasure Map) = -1
1947. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1948. ExecuteFirstEventAction = 0
1949. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1950. ExecuteFirstEventAction = 0
1951. StackResolveAction = 0
1952. AddEventAction (EVENT: Treasure Map  Move this card from the top of the library to the bottom?) = 0
1953. ChangeCountersAction = 0
1954. ExecuteFirstEventAction = 0
1955. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1956. ExecuteFirstEventAction = 0
1957. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1958. ExecuteFirstEventAction = 0
1959. StackResolveAction = 0
1960. PlayCardFromStackAction (Shielded Aether Thief) = -1100
1961. ChangeStateAction = 0
1962. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1963. ExecuteFirstEventAction = 0
1964. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1965. ExecuteFirstEventAction = 0
1966. AddEventAction (EVENT: NONE  Declare blockers.) = 0
Score = -1920

Exception from controller.runGame: ERROR! Inconsistent node found
GAME: id=0 t=18 p=DeclareBlockers s=ActivePlayer tp=0 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0 true true
java.lang.AssertionError: ERROR! Inconsistent node found
GAME: id=0 t=18 p=DeclareBlockers s=ActivePlayer tp=0 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0 true true
	at magic.ai.MCTSAI.growTree(MCTSAI.java:360)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:237)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:144)
	at magic.ai.MCTSAI.findNextEventChoiceResults(MCTSAI.java:148)
	at magic.headless.HeadlessGameController.getAIChoiceResults(HeadlessGameController.java:50)
	at magic.headless.HeadlessGameController.runGame(HeadlessGameController.java:33)
	at magic.DeckStrCal.runDuel(DeckStrCal.java:203)
	at magic.DeckStrCal.main(DeckStrCal.java:177)


  [2537/532/-822 at 10] ()
LOG (P): Tap <Treasure Map~1000013>. Pay {1}. Tap <Concealed Courtyard~1000028>. Play activated ability of <Treasure Map~1000013>.
MMAB cheat=true index=0 life=2 turn=18 phase=DeclareAttackers slice=1000 time=348
  [2538/435/-978 at 7] (yes)
* [2539/440/-815 at 9] (no)
LOG (P): MMABC scry 1. Put a landmark counter on <Treasure Map~1000013>. Then if there are three or more landmark counters on <Treasure Map~1000013>, remove those counters, transfrom <Treasure Map~1000013>, and create three colorless Treasure artifact tokens with "{T}, Sacrifice this artifact: Add one mana of any color to your mana pool." MMABC looks at the top card of his or her library and puts it back on top.
LOG (C): Put <Shielded Aether Thief~1000049> onto the battlefield.
CACHE HIT
HIT  : GAME: id=3895129117125391924 t=18 p=DeclareBlockers s=ActivePlayer tp=0 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0
18 1740826931 1100399456 0 0 1 0 -1 -1 -1 -568441775009488239 382790725146443516 382790725146443516 -3740896669022736994 -1053984883083174737 4713966540927895617 7944792183069476790 -4858377773034625298 -1501776584343065371 382790725146443516
2 0 0 0 0 0 0 0 0 1 7 1 0 0 1 5935152554327506905 -1634870246764637369 245728944309618855 382790725146443516 -2249278402615735002 0 -1 -1 0
5 0 0 0 0 0 0 0 0 0 7 1 0 2 0 6530807363359764629 674246361605116686 444133326838539 382790725146443516 -8109341300875433616 0 -1 -1 0
MCTS cached=97
 -> no
PAREN: S-1100 Grim Strider=Shielded Aether Thief
PAREN: S-99958099
CHILD: S-1100 Grim Strider=Shielded Aether Thief
CHILD: S-99958099
GAME : S-1100 Grim Strider=Shielded Aether Thief
GAME : S-3499
Makefile:229: recipe for target 'circleci' failed
make: *** [circleci] Error 1
Exited with code 2
```

**Comment by melvinzhang** [comment] 2018-03-23 01:27
This last one is pretty helpful, we can see that the cached game and the current game diverge during the declare blockers step. Specifically:
```
CHILD: S-1100 Grim Strider=Shielded Aether Thief
CHILD: S-99958099
GAME : S-1100 Grim Strider=Shielded Aether Thief
GAME : S-3499
```
The current game has a score of  -3499 for not blocking while in the cached game it should be -99958099 (a game loss).

**Comment by melvinzhang** [comment] 2018-03-23 02:10
I noticed on your firaga branch where this testing is occuring there are changes to MagicDeclareBlockersResultBuilder.java. It seems very likely that the bug here is caused by that as most of the cases here are related to blocking.

**Comment by Fulmene** [comment] 2018-03-23 07:56
[1521770613.zip](https://github.com/magarena/magarena/files/1840583/1521770613.zip)

This one diverged at the first main phase. It seems Underhanded Designs was missing from hand in the new game state.

**Comment by melvinzhang** [comment] 2018-03-23 08:09
Underhanded Designs is on the battlefield, the option is about activating its ability. The ability has a condition 'ability only if you control two or more artifacts'. It looks in in the current game, this ability can't be activated, but it could in the cached game.

**Comment by Fulmene** [comment] 2018-03-23 08:10
> I noticed on your firaga branch where this testing is occuring there are changes to MagicDeclareBlockersResultBuilder.java. It seems very likely that the bug here is caused by that as most of the cases here are related to blocking.

Yeah I think that's the most divergence from master. My intention is to implement Menace. Since my use case doesn't involve human player anyway, I figured I would intercept the result builder to exclude illegal results.

**Comment by Fulmene** [comment] 2018-03-23 08:24
From the game state, the condition was fulfilled (2 Servos) but there wasn't enough mana, so I presume the mana was enough in previous game state?

**Comment by melvinzhang** [comment] 2018-03-23 08:30
The state with the divergence looks like the next turn, as Swamp is an option. Meaning play Swamp from hand. So the lands would have been untapped.

**Comment by melvinzhang** [comment] 2018-03-23 08:36
See the out file, there is a description of the node that is inconsistent. The output string indicates the node is for turn 12 (t=12) and phase is first main (p=FirstMain).
```
GAME: id=0 t=12 p=FirstMain s=ActivePlayer tp=1 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0 true true 
``

**Comment by Fulmene** [comment] 2018-03-23 08:40
So the Underhanded Designs choice is play Swamp + its ability? It seems Swamp isn't in hand. I suspect it's because Commune with Dinosaurs pulled it from the library in the previous game state, but doesn't in the current one.

**Comment by melvinzhang** [comment] 2018-03-23 09:01
There is no need to play a Swamp as there is already two Swamps in play. 

Note that the game currently is at turn 11 declare blockers. The AI is considering future turns and in particular turn 12 first main. In the past when it considered turn 12 first main, it was able to activate Underhanded Designs. When it tries to advance the current game to turn 12 first main, Underhanded Designs is not an option.

**Comment by Fulmene** [comment] 2018-03-23 09:22
I'll copy turn 11 game state here for ease of reference.
```
Turn : 11  Phase : DeclareBlockers  Step : OtherPlayer  Player : MMAB  AI : monte carlo tree search (cheat)  Score : 3922
0] Player : MMAB  Life : 9  Delayed : Total=0
   - Hand : Cowl Prowler
   - Hand : Forest
   - Library : Ice Over
   - Library : Island
   - Library : Island
   - Library : Navigator's Ruin
   - Library : Rhonas's Last Stand
   - Library : Island
   - Library : Island
   - Permanent : Air Elemental  Power : 4  Toughness : 4  Damage : 0  Tapped
   - Permanent : Cogwork Assembler  Power : 2  Toughness : 3  Damage : 0  Tapped
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Island
   - Permanent : Island
   - Permanent : Island
   - Permanent : Seeker of Insight  Power : 1  Toughness : 3  Damage : 0  Tapped
   - Permanent : Tah-Crop Skirmisher  Power : 2  Toughness : 1  Damage : 0  Tapped
1] Player : MCTSC  Life : 5  Delayed : Total=0
   - Hand : Rhonas's Monument
   - Hand : Shed Weakness
   - Hand : Vengeful Rebel
   - Hand : Foundry Screecher
   - Graveyard : Commune with Dinosaurs
   - Library : Swamp
   - Library : Life Goes On
   - Library : Swamp
   - Library : Deadeye Tormentor
   - Library : Prizefighter Construct
   - Library : Lethal Sting
   - Library : Swamp
   - Permanent : Servo  Power : 1  Toughness : 1  Damage : 0  Summoned
   - Permanent : Servo  Power : 1  Toughness : 1  Damage : 0  Summoned
   - Permanent : Forest  Summoned
   - Permanent : Foul Orchard  Tapped
   - Permanent : Foul Orchard  Tapped
   - Permanent : Lurking Chupacabra  Power : 2  Toughness : 3  Damage : 0
   - Permanent : Swamp  Tapped
   - Permanent : Swamp  Tapped
   - Permanent : Underhanded Designs
   - Permanent : Weaponcraft Enthusiast  Power : 0  Toughness : 1  Damage : 0  Summoned
```

The path considered:
```
 -> S-3007 Seeker of Insight=Servo Tah-Crop Skirmisher=Weaponcraft Enthusiast Cogwork Assembler=Lurking Chupacabra+1 -> Shed Weakness -> Servo -> Forest -> Cowl Prowler
```

The choices considered here seem to be MCTSC used Shed Weakness on Servo so it survived blocking Seeker of Insight, which means the number of artifacts on its battlefield remained two (fulfilling the condition for Underhanded Designs). But the new game state doesn't allow the activation of Underhanded Designs?

**Comment by melvinzhang** [comment] 2018-03-23 09:27
That is correct and what I find puzzling as well. The Forest followed by Cowl Prowler are assumed by MCTS to be what MMAB does in second main of T11. Then the next node in the path is MCTS first main T12, where it is considering what to play/activate. Underhanded Designs should be valid choice at this point.

**Comment by Fulmene** [comment] 2018-03-26 03:02
[1521801357.zip](https://github.com/magarena/magarena/files/1846200/1521801357.zip)

Another one. This one occurred at declare blockers. It looks like the choices and the scores are exactly the same, but some choices are swapped?

**Comment by Fulmene** [comment] 2018-03-26 09:25
[1522042263.zip](https://github.com/magarena/magarena/files/1847160/1522042263.zip)

Also declare blockers. Two choices are labeled as CHILD but all of them are in GAME. What does it mean?

**Comment by melvinzhang** [comment] 2018-03-26 09:38
Generally CHILD should be a subset of PAREN and PAREN should be the same as GAME. In 1522042263, game has `S-3772 Grim Strider=Glory Seeker+1` that is not in PAREN.

**Comment by melvinzhang** [comment] 2018-03-26 09:40
> It looks like the choices and the scores are exactly the same, but some choices are swapped?

That's correct, the last two choices are in different order. The order must be the same as well.

**Comment by melvinzhang** [comment] 2018-03-26 09:41
@Fulmene since the error occurs quite frequently, could you test without the Menace changes? I want to confirm if it is indeed the cause.

**Comment by Fulmene** [comment] 2018-03-27 13:50
[1522152709.zip](https://github.com/magarena/magarena/files/1852216/1522152709.zip)

I tested without Menace changes. This one still crashed. The score for not blocking is inconsistent.

**Comment by Fulmene** [comment] 2018-04-14 04:29
I ran tests with only cheating AI for 24 hours, both with and without Menace changes, and haven't had any crashes. So I think these are actually the MCTS AI bug you mentioned in #1506.

I quickly rechecked the logs and found that the only ones not involving MCTS (honest) are those that reported `length of MCTS path is 1`: [CI build 471](https://circleci.com/gh/Fulmene/magarena/471) and [CI build 478](https://circleci.com/gh/Fulmene/magarena/478). And log 1521770613, the one that had missing Underhanded Designs choice.

**Comment by melvinzhang** [comment] 2018-04-14 04:50
Thanks for the investigation, closing this as duplicate of #1506 then.

**Closed by melvinzhang** 2018-04-14 04:50 UTC
Labels: bug
