### ISSUE TITLE
ClassCastException during CI test

### ISSUE THREAD

**Issue by Fulmene** [magarena/magarena#1473] opened 2018-02-17 20:47 UTC
https://circleci.com/gh/Fulmene/magarena/137

The stack trace doesn't mention any card, so I assume I'll need to look at the game state for the problem?

**Comment by melvinzhang** [comment] 2018-02-18 10:13
Thanks for creating the issue for this. Unfortunately, this is a known issue, the key is to watch out for mention of Surgespanner and `Exception from controller.runGame: java.lang.ClassCastException: magic.model.target.MagicTargetNone cannot be cast to magic.model.choice.MagicPayManaCostResult`. Closed as duplicate of #840

**Closed by melvinzhang** 2018-02-18 10:13 UTC
