### ISSUE TITLE
no artificial choice result for EVENT: Numai Outcast Pay {B}$

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#428] opened 2015-08-27 06:14 UTC
[broke build](https://buildhive.cloudbees.com/job/magarena/job/magarena/1594/console).
```
Exception from controller.runGame: no artificial choice result for EVENT: Numai Outcast Pay {B}$. Choose how to pay the mana cost.
java.lang.RuntimeException: no artificial choice result for EVENT: Numai Outcast Pay {B}$. Choose how to pay the mana cost.
	at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:88)
	at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:402)
	at magic.ai.MCTSAI.getNextChoices(MCTSAI.java:499)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:343)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment] 2015-08-27 06:18
duplicate of #226

**Closed by melvinzhang** 2015-08-27 06:18 UTC
Labels: AI, bug
