### ISSUE TITLE
encoding error in Tooth Collector

### ISSUE THREAD

**Issue by firemind** [magarena/magarena#804] opened 2016-07-14 21:56 UTC
While trying to flag the upcoming cards on firemind I stumbled across an encoding error in the oracle text property of Tooth_Collector.txt

The em dash after delirium seems to be incorrectly encoded. It displays it with the missing character question mark in the card explorer (ubuntu 16.04) and also here on github when looking at the raw view https://raw.githubusercontent.com/magarena/magarena/master/release/Magarena/scripts/Tooth_Collector.txt

Tested the card in a deck and it doesn't seem to cause a crash but since it's likely affecting other cards that were synced I wanted to let you know so you could maybe redo the sync for the oracle text of the new cards before the next release.

**Comment by melvinzhang** [comment] 2016-07-15 01:38
Thanks for reporting this. I can confirmed that Non-ISO characters are found in release/Magarena/scripts/Mindwrack_Demon.txt, release/Magarena/scripts/Tooth_Collector.txt, and release/Magarena/scripts/Topplegeist.txt

**Comment by melvinzhang** [comment] 2016-07-15 01:45
From the git history, it looks like these cards were added manually and not via the cardbuilder. So the error was probably introduced during copy-and-paste. I've manually fixed them.

**Comment by melvinzhang** [comment] 2016-07-15 01:46
fixed in https://github.com/magarena/magarena/commit/5678c8147d652bff87879e20ae3fcf968ad11203

**Closed by melvinzhang** 2016-07-15 01:45 UTC
