### ISSUE TITLE
Passing play with full stack

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1047] opened 2017-01-28 15:42 UTC
While #699 helps when there is a full stack with no play options available. If you right-click to pass until next phase, and you have a permanent that can be activated, you still have to click for each item on the stack.

**Comment by lodici** [comment] 2017-01-28 16:38
Sounds a bit like what does my head in. When you have a instant which keeps highlighting every phase which I understand why but sure gets annoying having to click to pass every time, especially on the AI's turn. Stop, start, stop, start...aarggh :boom: In the end I usually end up playing it just to speed things up a bit! I thought maybe an option to add a countdown timer which would activate each time Magarena prompts you for a decision and which counts down unless you move the mouse or something, in which case it pauses/cancels but if you let it reach zero then it automatically passes.

**Comment by ShawnieBoy** [comment] 2017-01-28 17:48
As we have right-clicking pass button to pass until end of turn (until there's a choice anyway) - What about right-clicking the offending spell/permanent, to skip its prompts the same way?

**Comment by lodici** [comment] 2017-01-28 18:13
Yes that sounds good and is consistent with the current pass clicks. For better consistency could then use left click to cancel the stack delay instead of the icon which I am not totally convinced about as a long term solution anyway - too small and a moving target due to the dynamic nature of the stack.

**Comment by melvinzhang** [comment] 2017-01-29 00:40
@lodici did you try the pass until end of turn? By right-clicking on the pass button on the AI's turn, it should pass until the AI play's something or attacks.

Perhaps we can improve the "pass until end of turn" heuristics. Currently it uses the fact that the stack has an item to indicate the AI played something so it should stop passing. This heuristic fails in this case because the stack is already populated and no one is playing anything so it should continue to auto pass.

**Comment by melvinzhang** [comment] 2017-01-29 01:08
I improved the check by only stopping "skip till EOT" when the AI actually plays something based on the move the AI makes rather than checking the stack. When I tried with TestBloodArtistWrath with addition of Lightning Bolt in hand, right click pass will skip through all the stack items without pausing for the Bolt. 

@ShawnieBoy Please check if it also works on your use case.

**Comment by ShawnieBoy** [comment] 2017-01-29 01:28
Yes - works a treat 😁

**Comment by melvinzhang** [comment] 2017-01-29 01:51
If this change resolves this issue, do close it. Thanks.

**Closed** 2017-01-29 13:31 UTC

**Comment by lodici** [comment] 2017-01-29 23:59
> @lodici did you try the pass until end of turn? By right-clicking on the pass button on the AI's turn, it should pass until the AI play something or attacks.

Not sure whether my issue is actually quite the same thing or even if there is a solution, your fix for this issue wasn't it unfortunately. I have been playing the 2012stompy deck which has Mutavault which once in play is highlighted and activates the 'play a card or ability' prompt nearly every phase (or so it seems). The timer is the only thing I thought of so far that could alleviate the constant need to click to pass with cards such as this.

**Comment by melvinzhang** [comment] 2017-01-30 00:34
As ShawnieBoy confirmed that the change worked for his issue, I think your is a different problem. Please create a new issue with a gameplay report.

**Comment by ShawnieBoy** [comment] 2017-01-30 03:25
> Not sure whether my issue is actually quite the same thing or even if there is a solution, your fix for this issue wasn't it unfortunately. I have been playing the 2012stompy deck which has Mutavault which once in play is highlighted and activates the 'play a card or ability' prompt nearly every phase (or so it seems). The timer is the only thing I thought of so far that could alleviate the constant need to click to pass with cards such as this.

Right-clicking the end turn should skip those phases. Mine was with [Quest for Ancient Secrets](http://magiccards.info/zen/en/59.html) which should be the same with all activated abilities interrupting the stack.

**Comment by lodici** [comment] 2017-01-30 12:18
I am not even sure if the behaviour is not by design (so is not an issue) but here is a gameplay report with Mutavault in play at M1 on my turn. Right click pass and it runs to ET and stops. Right click pass and runs to UP on AI's turn. Right click pass and runs to M1 and stops. Right click pass and runs to DA and stops. Right click pass and runs to DB and stops. Right click pass and runs to ET and stops. Right click pass and runs to UP on my turn and stops. Right click pass and runs to ET and stops. And so on....
[gameplay-report.zip](https://github.com/magarena/magarena/files/738863/gameplay-report.zip)

**Comment by ShawnieBoy** [comment] 2017-01-30 15:55
I think this is mainly by design, it's to do with the timings for animating a permanent into a creature. But it does look as though it's not very efficient.

I'm not sure why it stops during the UP of the opponent's turn. Especially considering if the ET of your turn is right-clicked. This may be simply a reset of the pause mechanic, and starting again on the first phase where you get priority again.

The M1 of the opponent's turn is due to not having the BC phase implemented in Magarena. This would be the time to animate a permanent to be able to declare it as an attacker during the DA phase, otherwise it would be too late. But there's no need to pause on the opponent's turn, only on yours.

The DA of the opponent's turn is the last moment you can animate to be able to block.

It will always stop at ET if there's something that can be activated/cast - it's a catch if the whole turn has been skipped, and acts a final confirmation to end the turn.

Could certainly do with some tidying up - I'll see if I can find where all this happens.
