### ISSUE TITLE
tooth and nail

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#460] opened 2015-10-01 08:29 UTC
with entwine the options trigger in the wrong order you have to put creatures into play before you search for them which is wrong.

AI MCTS searches for non creatures and puts them into its hand e.g. bonfire of the damned.

**Comment by ShawnieBoy** [comment] 2015-11-08 22:58
I've had a fiddle with this, and even when swapping the order of the effects in the groovy code, it will still ask for the play from hand first.

I'm wondering if it needs a kind of game.update() in between the two effects to ensure that the search occurs first if it is entwined.

**Comment by ShawnieBoy** [comment] 2015-11-08 23:01
essentially duplicate of #281

**Closed** 2015-11-09 01:49 UTC
Labels: bug, card, groovy
