### ISSUE TITLE
MCTSAI.growTree IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#421] opened 2015-08-18 05:30 UTC
full game and crash log available in [forum post](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17490&p=184352&sid=05213ee53a4e61dc6ee8c8cb0001164a#p184352).
```
...
1220. TapAction (Dismal Backwater) = 5
1221. TapAction (Island) = 5
1222. TapAction (Swamp) = 5
1223. TapAction (Swamp) = 5
1224. TapAction (Watery Grave) = 5
1225. ExecuteFirstEventAction = 0
1226. RemoveCardAction (Nyxborn Triton) = 301
1227. PutItemOnStackAction (,Nyxborn Triton) = 1
1228. AddEventAction (EVENT: Nyxborn Triton  Choose target creature.) = 0
1229. AddEventAction (EVENT: Nyxborn Triton  ) = 0
Score = 3354

Exception from controller.runGame: Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:404)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment] 2015-08-18 05:50
duplicate of #307

**Closed by melvinzhang** 2015-08-18 05:50 UTC
Labels: AI, bug
