### ISSUE TITLE
MagicBuilderManaCost.compress - AssertionError: typeCount is inconsistent...

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#517] opened 2015-11-24 15:11 UTC
On starting an AI vs AI game. Have not been able to replicate - subsequent AI games have run fine.

```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-3-thread-3,5,main]
CREATED ON 2015/11/24 15:02:52
MAGARENA VERSION 1.68, JRE 1.8.0_51, OS Windows 7_6.1 x86
================================
Used Memory: 141M
Free Memory: 67M
Total Memory: 208M
Max Memory: 494M
================================
-Dfile.encoding=UTF-8
-DselfMode=true
-DdevMode=true
-Dmagarena.dir=release
-ea
-Xmx512m


Turn : 1  Phase : FirstMain  Step : ActivePlayer  Player : Mini Max  Score : 78
0] Player : Mini Max  Life : 20  Delayed : Total=0
   - Hand : Woodland Cemetery
   - Hand : Abandoned Outpost
   - Hand : Island
   - Hand : Breeding Pool
   - Hand : Daggerdrome Imp
   - Hand : Netherborn Phalanx
1] Player : Mini Max  Life : 20  Delayed : Total=0
   - Hand : Zombify
   - Hand : Darkslick Shores
   - Hand : Jwar Isle Refuge
   - Hand : Nephalia Drownyard
   - Hand : Sheoldred, Whispering One
   - Hand : Zombify
Stack : 0
1. AddEventAction (EVENT: NONE Mini Max may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE Mini Max may$ take a mulligan. ) = 0
3. ExecuteFirstEventAction = 0
4. ShiftCardAction = 0
5. RemoveCardAction (Vivid Creek) = -535
6. MoveCardAction (Vivid Creek,OwnersHand,OwnersLibrary) = 0
7. ShuffleIntoLibraryAction = 0
8. ShiftCardAction = 0
9. RemoveCardAction (Goblin War Wagon) = -69
10. MoveCardAction (Goblin War Wagon,OwnersHand,OwnersLibrary) = 0
11. ShuffleIntoLibraryAction = 0
12. ShiftCardAction = 0
13. RemoveCardAction (Breeding Pool) = -506
14. MoveCardAction (Breeding Pool,OwnersHand,OwnersLibrary) = 0
15. ShuffleIntoLibraryAction = 0
16. ShiftCardAction = 0
17. RemoveCardAction (Thornwood Falls) = -466
18. MoveCardAction (Thornwood Falls,OwnersHand,OwnersLibrary) = 0
19. ShuffleIntoLibraryAction = 0
20. ShiftCardAction = 0
21. RemoveCardAction (Woodland Cemetery) = -494
22. MoveCardAction (Woodland Cemetery,OwnersHand,OwnersLibrary) = 0
23. ShuffleIntoLibraryAction = 0
24. ShiftCardAction = 0
25. RemoveCardAction (Abandoned Outpost) = -462
26. MoveCardAction (Abandoned Outpost,OwnersHand,OwnersLibrary) = 0
27. ShuffleIntoLibraryAction = 0
28. ShiftCardAction = 0
29. RemoveCardAction (Seaside Citadel) = -636
30. MoveCardAction (Seaside Citadel,OwnersHand,OwnersLibrary) = 0
31. ShuffleIntoLibraryAction = 0
32. DrawAction = 2399
33. AddEventAction (EVENT: NONE Mini Max may$ take a mulligan. ) = 0
34. ExecuteFirstEventAction = 0
35. ShiftCardAction = 0
36. RemoveCardAction (Jwar Isle Refuge) = 465
37. MoveCardAction (Jwar Isle Refuge,OwnersHand,OwnersLibrary) = 0
38. ShuffleIntoLibraryAction = 0
39. ShiftCardAction = 0
40. RemoveCardAction (Swamp) = 375
41. MoveCardAction (Swamp,OwnersHand,OwnersLibrary) = 0
42. ShuffleIntoLibraryAction = 0
43. ShiftCardAction = 0
44. RemoveCardAction (Thought Scour) = 435
45. MoveCardAction (Thought Scour,OwnersHand,OwnersLibrary) = 0
46. ShuffleIntoLibraryAction = 0
47. ShiftCardAction = 0
48. RemoveCardAction (Sheoldred, Whispering One) = 371
49. MoveCardAction (Sheoldred, Whispering One,OwnersHand,OwnersLibrary) = 0
50. ShuffleIntoLibraryAction = 0
51. ShiftCardAction = 0
52. RemoveCardAction (Recurring Nightmare) = 480
53. MoveCardAction (Recurring Nightmare,OwnersHand,OwnersLibrary) = 0
54. ShuffleIntoLibraryAction = 0
55. ShiftCardAction = 0
56. RemoveCardAction (Go for the Throat) = 677
57. MoveCardAction (Go for the Throat,OwnersHand,OwnersLibrary) = 0
58. ShuffleIntoLibraryAction = 0
59. ShiftCardAction = 0
60. RemoveCardAction (Platinum Angel) = 380
61. MoveCardAction (Platinum Angel,OwnersHand,OwnersLibrary) = 0
62. ShuffleIntoLibraryAction = 0
63. DrawAction = -2336
64. AddEventAction (EVENT: NONE Mini Max may$ take a mulligan. ) = 0
65. ExecuteFirstEventAction = 0
66. ExecuteFirstEventAction = 0
67. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
68. ExecuteFirstEventAction = 0
69. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
70. ExecuteFirstEventAction = 0
71. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = 78

Exception from controller.runGame: typeCount is inconsistent: typeCount = 3, compressedIndex = 2
java.lang.AssertionError: typeCount is inconsistent: typeCount = 3, compressedIndex = 2
	at magic.model.choice.MagicBuilderManaCost.compress(MagicBuilderManaCost.java:52)
	at magic.model.MagicManaCost.addTo(MagicManaCost.java:315)
	at magic.model.MagicManaCost.getBuilderCost(MagicManaCost.java:303)
	at magic.model.condition.MagicManaCostCondition.accept(MagicManaCostCondition.java:23)
	at magic.model.event.MagicPayManaCostEvent.isSatisfied(MagicPayManaCostEvent.java:39)
	at magic.model.event.MagicActivation.canPlay(MagicActivation.java:108)
	at magic.model.event.MagicSourceActivation.canPlay(MagicSourceActivation.java:26)
	at magic.model.choice.MagicPlayChoice.addValidChoices(MagicPlayChoice.java:78)
	at magic.model.choice.MagicPlayChoice.getArtificialOptions(MagicPlayChoice.java:68)
	at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:86)
	at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:402)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:207)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:188)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:188)
	at magic.ai.MMAB$MMABWorker.evaluateGame(MMAB.java:260)
	at magic.ai.MMAB$1.run(MMAB.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment] 2015-11-25 01:24
duplicate of #431

**Closed by melvinzhang** 2015-11-25 01:24 UTC
Labels: bug
