### ISSUE TITLE
reforge the soul

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#770] opened 2016-05-29 14:15 UTC
Discards hand draws 7 and then discards hand again will have a look at script and see if I can fix it.
This was when cast using miracle.  Can't see what's wrong with the script unless it is putting the abilities onto the stack before executing and thus they happen in the wrong order.

**Comment by melvinzhang** [comment] 2016-05-29 14:18
To clarify, what you observed is

"discard hand, draw 7, discard hand"

whereas what should occur is

"discard hand, draw 7"

There is an additional discard hand, is this the issue?

**Comment by Muppet1** [comment] 2016-05-29 15:01
not absolutely sure the final situation is you have drawn 7 and then discarded your hand not absolutely sure of individual steps.  I just tried swapping the order of the effects in the script and will see what happens now.

**Comment by Muppet1** [comment] 2016-06-07 10:08
can fix it with groovy if necessary Tolarian Winds is fine for example

**Comment by ShawnieBoy** [comment] 2016-06-07 11:41
This looks as though it's related to the timing issues with discard and draw if scripted, actions and effects resolving in an order that isn't expected #205 #396 #764

**Comment by melvinzhang** [comment] 2016-06-07 13:50
In Tolarian Windows both Discard and Draw are events. Perhaps we should just make the Draw effect always use an event instead of an action.

**Comment by ShawnieBoy** [comment] 2016-06-07 14:27
It's certainly worth a try - Was the only way I could get them to occur in the correct order.

**Comment by Muppet1** [comment] 2016-06-09 10:24
I uploaded a working Reforge the Soul with groovy to firemind.
I'll try Wheel of Fortune next.

**Comment by melvinzhang** [comment] 2016-06-09 11:40
duplicate of #205

**Closed by melvinzhang** 2016-06-09 11:40 UTC
