### ISSUE TITLE
using locale sensitive toUpperCase() and toLowerCase() for locale independent code

### ISSUE THREAD

**Issue by destdest** [magarena/magarena#959] opened 2016-10-26 11:34 UTC
New clean pc windows 7 x64 and first java install latest version. I click the game and then fatal error message, help me pls,
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-1-thread-1,5,main]
CREATED ON 2016/10/26 13:43:52
MAGARENA VERSION 1.77, JRE 1.8.0_111, OS Windows 7_6.1 amd64
================================
Used Memory: 35M
Free Memory: 210M
Total Memory: 245M
Max Memory: 455M
================================
-Xms256m
-Xmx512m
-Xverify:none


Exception from controller.runGame: java.lang.RuntimeException: Error loading C:\Users\Acer\Downloads\Magarena-1.77\Magarena\scripts\0_0_black_Germ_creature_token.txt
java.lang.RuntimeException: java.lang.RuntimeException: Error loading C:\Users\Acer\Downloads\Magarena-1.77\Magarena\scripts\0_0_black_Germ_creature_token.txt
	at magic.utility.MagicSystem$2.done(MagicSystem.java:55)
	at java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
	at java.util.concurrent.FutureTask.setException(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error loading C:\Users\Acer\Downloads\Magarena-1.77\Magarena\scripts\0_0_black_Germ_creature_token.txt
	at magic.data.CardDefinitions.loadCardDefinition(CardDefinitions.java:180)
	at magic.data.CardDefinitions.loadCardDefinitions(CardDefinitions.java:205)
	at magic.utility.MagicSystem.initializeEngine(MagicSystem.java:145)
	at magic.utility.MagicSystem.access$100(MagicSystem.java:24)
	at magic.utility.MagicSystem$1.run(MagicSystem.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	... 4 more
Caused by: java.lang.RuntimeException: unknown card property value "image_updated" = "2015-11-12"
	at magic.data.CardDefinitions.setProperty(CardDefinitions.java:95)
	at magic.data.CardDefinitions.prop2carddef(CardDefinitions.java:122)
	at magic.data.CardDefinitions.loadCardDefinition(CardDefinitions.java:174)
	... 9 more
```

**Comment by lodici** [comment] 2016-10-26 12:02
see also #788 - was unable to reproduce. Could it be a locale or encoding issue?

**Comment by lodici** [comment] 2016-10-26 13:13
It falls over on "image_updated" only because it is the first property to be read in a sorted list. I am able to artificially replicate the exact same error message by adding a space to the end of the property name as shown below (in CardDefinitions)...
```
    private static void setProperty(final MagicCardDefinition card,final String property,final String value) {
        try {
            CardProperty.valueOf(property.toUpperCase() + " ").setProperty(card, value);
        } catch (IllegalArgumentException e) {
            throw new RuntimeException("unknown card property value \"" + property + "\" = \"" + value + "\"");
        }
    }
```
However changing the script file by adding a space or altering the encoding used has so far produced no error. Maybe a permissions issue, then?

**Comment by melvinzhang** [comment] 2016-10-27 01:34
My best guess it has to do with locale, we use toUpperCase to convert the property name to an enum value but we did not specify the locale so it uses the system's one. We should specify Locale.ENGLISH.

**Comment by melvinzhang** [comment] 2016-10-27 01:37
https://docs.oracle.com/javase/8/docs/api/java/lang/String.html writes: "This method is locale sensitive, and may produce unexpected results if used for strings that are intended to be interpreted locale independently. "

**Comment by melvinzhang** [comment] 2016-10-27 01:53
@destdest What's the system locale setting on your computer? 

You can view your system locale following the instructions at https://java.com/en/download/help/locale.xml

**Comment by destdest** [comment] 2016-10-27 01:55
Windows 7 Turkish, i<İ , ı<I

**Comment by destdest** [comment] 2016-10-27 01:58
thanks it works

**Comment by melvinzhang** [comment] 2016-10-27 01:59
@destdest Thanks for the quick response. I think this nails it then, we converted the lower i to the uppercase dotted i which did not match what we defined in the code.

**Comment by destdest** [comment] 2016-10-27 02:03
Yes, Changing the System Locale in Windows 7 youtube, Turkish to English American, and it works thanks alot again.

**Comment by melvinzhang** [comment] 2016-10-27 02:06
Yup, that should do it for now. We will fix the locale bug in our code for the next release.

**Comment by destdest** [comment] 2016-10-27 02:08
Ok see you.

**Comment by melvinzhang** [comment] 2016-10-27 03:09
ed02b9958929747f4 address the problem to toLowerCase

**Comment by melvinzhang** [comment] 2016-10-27 03:24
Tested on Linux with tr_TR.UTF-8 locale. Previously it would crash, with the fixed it runs correctly @lodici could you help to test on Windows?

**Comment by lodici** [comment] 2016-10-27 07:19
I am not able to test directly on Windows, I tried setting the system locale to turkish on Windows 7 running in vbox but it did not make any difference, it still worked. I am pretty sure though that you have fixed the problem based on the op's feedback so I think we can close this and #788. Nice work.

**Closed by lodici** 2016-10-27 07:19 UTC
Labels: bug
