### ISSUE TITLE
TestShuriken creates AI crash

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#427] opened 2015-08-21 16:15 UTC
CRASH REPORT FOR MAGARENA THREAD Thread[pool-2-thread-1,5,main]
CREATED ON 2015/08/21 17:13:39
MAGARENA VERSION 1.64, JRE 1.8.0_45, OS Windows 8.1_6.3 amd64
================================
Used Memory: 341M
Free Memory: 134M
Total Memory: 476M
Max Memory: 910M
================================
-Xms256M
-Xmx1g
-DtestGame=TestShuriken

Turn : 24  Phase : FirstMain  Step : ActivePlayer  Player : MCTS  Score : -2756
0] Player : Player  Life : 20  Delayed : Total=0
   - Hand : Traproot Kami
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Traproot Kami  Power : 0  Toughness : 8  Damage : 0
1] Player : MCTS  Life : 20  Delayed : Total=0
   - Hand : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Traproot Kami  Power : 0  Toughness : 8  Damage : 0
   - Permanent : Shuriken
   - Permanent : Shuriken
Stack : 0
1.  (Forest) = 712
2.  (Forest) = 712
3.  (Forest) = 712
4.  (Forest) = 712
5.  (Traproot Kami) = 1140
6.  (Forest) = -712
7.  (Forest) = -712
8.  (Forest) = -712
9.  (Forest) = -712
10.  (Traproot Kami) = -1940
11.  (Shuriken) = -772
12.  (Shuriken) = -772
13. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
14. ExecuteFirstEventAction = 0
15. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
16. ExecuteFirstEventAction = 0
17. DrawAction = -412
18. AddEventAction (EVENT: NONE  ...) = 0
19. ExecuteFirstEventAction = 0
20. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
21. ExecuteFirstEventAction = 0
22. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
23. ExecuteFirstEventAction = 0
24. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = -2756

Exception from controller.runGame: Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:404)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by lodici** [comment] 2015-08-21 16:30
I am running with assertions enabled (``-ea``). It starts on UP but as soon as I move to M1 it falls over with an ``AssertionError`` -
```
Exception from controller.runGame: ERROR! Inconsistent node found
GAME: id=0 t=24 p=SecondMain s=ActivePlayer tp=1 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0 true true
java.lang.AssertionError: ERROR! Inconsistent node found
GAME: id=0 t=24 p=SecondMain s=ActivePlayer tp=1 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0 true true
	at magic.ai.MCTSAI.growTree(MCTSAI.java:351)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
Is the test set up correctly?

**Comment by ShawnieBoy** [comment] 2015-08-21 17:23
The test is fine which is the bizarre thing, and only crashes when it's the AI's turn. Assuming it's something to do with the Shuriken as it's little different from TestLifespinner which I used as a base

**Comment by melvinzhang** [comment] 2015-08-22 00:44
Great test, it allows us to generate #307 in a reliable way. Closing this as a duplicate of #307

**Closed by melvinzhang** 2015-08-22 00:44 UTC
Labels: AI, java
