### ISSUE TITLE
IndexOutOfBoundsException in MCTSAI.growTree

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#809] opened 2016-07-17 13:30 UTC
With Magarena 1.74, just got this crash:

```
Exception from controller.runGame: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
magic.exception.GameException: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at magic.ai.MCTSAI.growTree(MCTSAI.java:421)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:240)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:417)
	... 5 more
```

Issue #307 appears similar, but it looks like it's supposed to have been fixed.

Full logs attached.
[crashlog.zip](https://github.com/magarena/magarena/files/367849/crashlog.zip)

**Comment by melvinzhang** [comment] 2016-07-18 01:41
Thanks for the report. It looks like the problem is caused by blocking order not captured in the game id value. MCTS uses a game id to reuse previously encountered game states. The current game id value does not take into account the blocking order. 

In this case, I suspect that two different game states with different blocking order have the same value, this causes MCTS to reuse a wrong game state which eventually diverged as lead to the crash.

The fix is to include the blocking order as part of the game value.

**Comment by melvinzhang** [comment] 2016-07-18 12:44
Fixed in https://github.com/magarena/magarena/commit/a3e264cecc555e148e08e542efbde7307b2c734a

**Closed by melvinzhang** 2016-07-18 12:44 UTC
